### PR TITLE
Move comparison-component dependency to devDependency

### PR DESCRIPTION
**Pull request by chujimmy**
Hey @oliverviljamaa, 

`comparison-component` is now available in on the private @transferwise npm repo (and GitHub tag is about to be deprecated), `comparison-component` has been moved as a devDependency (as only the `dist` folder is need in `frontend-apps`).

WDYT ? 

I will recreate / update the tag to keep consistency between `comparison-component` and `comparison-component-angular` version.

### CODE REVIEW

**Comment by oliverviljamaa** [comment]
Do you know why the GitHub tag would need to be deprecated?
Do you also know why we have it under the private organization?
Wouldn't it be wise to add CircleCI to the process now for the build?

**Comment by chujimmy** [comment]
I can imagine the GitHub tag is deprecated as the scalable acquisition team doesn't want to maintain 2 different ways to release of a new version as npm is used in lienzo for now.

As for the private organisation, that's something to be asked to the scalable acquisition team but since `comparison-component` and `comparison-component-angular` are public, there is no reason to have it under a private organization. 

CircleCI could be added, but some tests need to be written then !

**Comment by daves125125** [comment]
Hey guys, so as Jimmy said we (scalable) opted to move towards just supporting the npm package due to the way in which we now package translations. As part of our CI (using circle) we download all language files (from crowdin) and integrate these into our bundled js file for the comparison component - these translations don't (and shouldn't) live as part of source, hence we wanted to move away from supporting tags.

The choice for a private npm repo over a public one was for two reasons, firstly we wanted to ensure we had the process working smoothly and had components packaged properly before making public and secondly because we plan to eventually transition to using an updatable script as the defacto form of distribution (that will pull the latest version of the component / widget into a page on each render). This will make it much easier to maintain working versions across the TW sites and allow us to pass to external parties such as affiliates when needed.

Of course we're happy for any feedback on the above, want to make sure we're making it as easy as possible for people to use this.

**Comment by oliverviljamaa** [comment]
Thanks, all good, just wanted to understand this better!

Do you think the comparison components for Angular should live in the main `comparison-components` package as well so it would be more easily maintained?

**Comment by daves125125** [comment]
Yeh I think possibly so in the future, I wasn't aware of this repo until today :)

In the medium term though I feel a script based solution could avoid the need for this entirely if we sandbox the dependencies and make it lightweight enough to use. (If my understanding of the purpose of this repo being to wrap the react component for angular compatibility, is correct).

**Pull request merged**
